# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates to Poetry dependencies every week
      interval: "weekly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: direct
      - dependency-type: indirect

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/.clusterfuzzlite/"
    schedule:
      # Check for updates to Docker images every month
      interval: "monthly"
