# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options 
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: What's new 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🕷
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
