name: Build
on:
  pull_request:
  push:
    branches:
    - main
  workflow_call:

permissions: {}  # No permissions needed for this workflow.

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.9', '3.10', '3.11']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        run: ./scripts/build.sh
        env:
          OUTPUT_ENV_VAR: ${{ (matrix.python-version == '3.10' && 'GITHUB_OUTPUT') || '' }}
      # The next two steps only run if OUTPUT_ENV_VAR (above) has a value.
      - name: Archive build artifacts
        if: ${{ success() && steps.build.outputs.version }}
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: dist
          path: dist/
      - name: Report to Coveralls
        if: ${{ success() && steps.build.outputs.coverage-lcov }}
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: ${{ steps.build.outputs.coverage-lcov }}
