name: Build
on:
  pull_request:
  push:
    branches:
    - main
  workflow_call:

permissions: {}  # No permissions needed for this workflow.

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        run: ./scripts/build.sh
      - name: Generate coverage
        run: |
          . .venv/bin/activate
          coverage lcov
      - name: Archive build files (Python 3.10 only)
        if: ${{ success() && matrix.python-version == '3.10' }}
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: build-artifacts
          path: |
            coverage.lcov
            dist/

  coverage:
    name: Report coverage to coveralls.io
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: Report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage.lcov
