name: Build
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:  # These will run in publish.yml.
      - .github/**
      - pyproject.toml
      - scripts/build.sh
  workflow_call:
    outputs:
      version:
        description: "Version of built module"
        value: ${{ jobs.build.outputs.version }}

permissions: {}  # No permissions needed for this workflow.

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.version }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4.6.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        id: build
        env:
          OUTPUT_ENV_VAR: GITHUB_OUTPUT
        run: ./scripts/build.sh
      - name: Check for code modifications
        if: always()
        id: modified
        run: |
          # exit 0 if nothing was modified.
          [ -z "$(git diff-index "${GITHUB_SHA}")" ] && exit 0

          # Copy modified files to ./.cache/diff. This path is in .gitignore
          rm -fR ./.cache/diff && mkdir --parents ./.cache/diff
          git diff-index -z --name-only --diff-filter=M "${GITHUB_SHA}" | \
            xargs -0 cp --parents -t ./.cache/diff/ -- 2>/dev/null && \
            echo "build-changes=./.cache/diff/" | tee -a "$GITHUB_OUTPUT"

          echo "FAIL: Files were changed during the Build step"
          echo "Please ensure pre-commit was run on these changes"
          exit 1
      - name: Archive code modifications
        if: failure() && steps.modified.outputs.build-changes
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: build-changes-${{ matrix.python-version }}
          path: ${{ steps.modified.outputs.build-changes }}
      - name: Archive build artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          if-no-files-found: error
          name: dist-${{ matrix.python-version }}
          path: dist/
      - name: Archive coverage results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          if-no-files-found: error
          name: coverage-${{ matrix.python-version }}
          path: ${{ steps.build.outputs.coverage-lcov }}

  # Coverage reporting is its own step so it can optionally fail if coveralls
  # is experiencing issues. pyWeMo doesn't currently have any logic that is
  # different between Python versions, so the coverage output from only one
  # version needs to be reported. Change the artifact name to use the coverage
  # from a different matrix build version.
  coverage:
    name: Report coverage to coveralls.io
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: coverage-3.10
      - uses: coverallsapp/github-action@f350da2c033043742f89e8c0b7b5145a1616da6d # v2.1.2
        with:
          path-to-lcov: coverage.lcov
