name: ClusterFuzzLite

on:
  push:
    paths:
      - .github/workflows/fuzz.yml
      - .clusterfuzzlite/**
      - pywemo/**.py
      - tests/**_fuzz.py
  pull_request:
    paths:
      - .github/workflows/fuzz.yml
      - .clusterfuzzlite/**
      - pywemo/**.py
      - tests/**_fuzz.py
  schedule:
    - cron: '27 3 * * *'  # Daily.

permissions: read-all

jobs:
  fuzz:
    name: Fuzzing
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.event_name }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
        - address
        # - undefined
        # - memory
    steps:
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
      with:
        language: python
        github-token: ${{ secrets.GITHUB_TOKEN }}
        sanitizer: ${{ matrix.sanitizer }}
        upload-build: ${{ github.event_name == 'push' }}

    - name: Run Fuzzers (${{ matrix.sanitizer }})
      id: run
      if: github.event_name != 'push'
      uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: ${{ github.event_name == 'schedule' && 3600 || 600 }}
        mode: ${{ github.event_name == 'schedule' && 'batch' || 'code-change' }}
        sanitizer: ${{ matrix.sanitizer }}
