name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yml
      - poetry.lock
      - scripts/common.sh
      - pywemo/**

permissions: {}  # No permissions by default. Permissions are added per-job.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          # NOTE: We use 3.10+ typing syntax via future, which pdoc only
          # understands if it's actually run with Python 3.10 or newer.
          python-version: ">= 3.10"

      - name: Enable build input caching
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            ./.cache/pip
            ./.cache/pypoetry
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: setup
        env:
          OUTPUT_ENV_VAR: GITHUB_OUTPUT
          PIP_CACHE_DIR: ./.cache/pip
          POETRY_CACHE_DIR: ./.cache/pypoetry
        run: |
          source ./scripts/common.sh
          assertPython
          enterVenv
          poetryInstall

      - name: build docs
        run: |
          source ./scripts/common.sh
          enterVenv
          pdoc -o ./html -d google ./pywemo/

      - name: upload docs artifact
        uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2.0.0
        with:
          path: ./html/

  # This is copied from the official `pdoc` example:
  #   https://github.com/mitmproxy/pdoc/blob/main/.github/workflows/docs.yml
  #
  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # NOTE: Needed to push to the repository.
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@9dbe3824824f8a1377b8e298bafde1a50ede43e5 # v2.0.4
