name: Publish
on:
  release:
    types: [published]
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  check:
    name: Check version and tag match
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version: ${{ steps.outputs.outputs.version }}
      artifact: ${{ steps.outputs.outputs.artifact }}
    steps:
      - name: Set Outputs
        id: outputs
        run: |
          echo "artifact=dist-files-3.10" | tee -a "$GITHUB_OUTPUT"
          echo "version=$GITHUB_REF_NAME" | tee -a "$GITHUB_OUTPUT"
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.outputs.outputs.artifact }}
          path: dist
      - name: Check if tag version matches project version
        working-directory: dist
        run: |
          # Get the version from the PKG-INFO in the source package.
          tar -xzf *.tar.gz
          DIST_VERSION=$(sed -ne 's/^Version: \([0-9]\..*\)$/\1/p' < */PKG-INFO | head -1)
          echo "TAG: $GITHUB_REF_NAME"
          echo "VERSION: $DIST_VERSION"
          if [[ "$GITHUB_REF_NAME" != "$DIST_VERSION" ]]; then exit 1; fi

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: check
    environment: release
    permissions:
      id-token: write # For Sigstore & PyPI trusted publishing
      contents: write # For adding assets to the github release
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.check.outputs.artifact }}
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@a56da0b891b3dc519c7ee3284aff1fad93cc8598 # v1.8.6
      - name: Generate Checksums
        working-directory: dist
        run: sha256sum * | tee sha256sums.txt
      - name: Sign the release
        uses: sigstore/gh-action-sigstore-python@e323e1b02e26cc6600843935562c862b94200b0c # v1.2.3
        with:
          inputs: ./dist/*
          release-signing-artifacts: true
          bundle-only: true
