name: Publish
on:
  release:
    types: [created]
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  check:
    name: Check version and tag match
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version: ${{ steps.outputs.outputs.version }}
      artifact: ${{ steps.outputs.outputs.artifact }}
    steps:
      - name: Set Outputs
        id: outputs
        run: |
          echo "artifact=dist-files-3.10" | tee -a "$GITHUB_OUTPUT"
          echo "version=$GITHUB_REF_NAME" | tee -a "$GITHUB_OUTPUT"
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.outputs.outputs.artifact }}
          path: dist
      - name: Check if tag version matches project version
        working-directory: dist
        run: |
          # Get the version from the PKG-INFO in the source package.
          tar -xzf *.tar.gz
          DIST_VERSION=$(sed -ne 's/^Version: \([0-9]\..*\)$/\1/p' < */PKG-INFO | head -1)
          echo "TAG: $GITHUB_REF_NAME"
          echo "VERSION: $DIST_VERSION"
          if [[ "$GITHUB_REF_NAME" != "$DIST_VERSION" ]]; then exit 1; fi

  assets:
    name: Add assets to Release
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.check.outputs.artifact }}
          path: dist
      - name: Generate Checksums
        working-directory: dist
        run: sha256sum * | tee sha256sums.txt
      - name: Add assets to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: check
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.check.outputs.artifact }}
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
