name: Publish
on:
  release:
    types: [created]
jobs:
  deploy:
    name: Build, test, and deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build and publish
        env:
          CI: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_SERVICE_NAME: github
          COVERALLS_PARALLEL: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/build_and_publish.sh ${{ secrets.PYPI_PASSWORD }}
  coveralls:
    name: Indicate completion to coveralls.io
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Finished
        env:
          COVERALLS_SERVICE_NAME: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish
