name: Publish
on:
  release:
    types: [created]
jobs:
  deploy:
    name: Build, test, and deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build
        run: ./scripts/build.sh
      - name: Generate coverage
        run: |
          . .venv/bin/activate
          coverage lcov
      - name: Report Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage.lcov
      - name: Publish
        run: |
          . .venv/bin/activate
          poetry publish --username __token__ --password "${{ secrets.PYPI_PASSWORD }}"
